### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by Diazonium** [CLRX/CLRX-mirror#1]
Is there any chance for Windows support?

**Comment by matszpk** [comment]
Yes. But later. Not in the next release, but later. Even before end of this year. I assume that code (including clwrapper) is portable and only small changes will be needed to port to windows.

**Comment by matszpk** [comment]
Tentatively, CLRadeonExtender has been compiled and tested under Windows 8.1 and Visual Studio 2015 Community. Tests has been passed!
