### ISSUE TITLE
Could you add more information about Global Data Share (GDS)?

### ISSUE THREAD

**Issue by zawawawa** [CLRX/CLRX-mirror#12]
I was wondering if you know how to enable GDS on Windows and/or Linux. I tried everything I can think of to access GDS, but specifying "enable_ordered_append_gds" and "workgroup_group_segment_byte_size" does not seem to be enough.  Please see the following for the context of this request:

https://community.amd.com/thread/170216
https://bitcointalk.org/index.php?topic=1716584

**Comment by matszpk** [comment]
I was playing with GDS on older AMD OpenCL 1.2 with my assembler. Just I initialized size of GDS by setting M0: `s_mov_b32 m0, 0xffff` (look up at 3.7 chapter in AMD GCN ISA) before any access without specifying any special setup. I didn't make any tests on AMD OCL 2.0.

**Comment by zawawawa** [comment]
Thanks for the info! I did try `s_mov_b32 m0, 0xffff` with RX 480 and Crimson 16.9.2, but that didn't work. I will try again with the "-legacy" option. Which video card and driver were you using?

**Comment by matszpk** [comment]
I was testing GDS code on old Pitcairn and old Crimson 15.12 or older driver on Linux.

**Comment by zawawawa** [comment]
That makes sense as people are having difficulty accessing GDS on GCN2/3/4 devices. The "-legacy" option didn't work, either. If you ever figure out how to enable GDS on newer video cards, please let me know!

**Comment by zawawawa** [comment]
I just confirmed that GDS on 7990 was accessible, so the aforementioned restriction must be specific to GCN2+ devices.

**Comment by zawawawa** [comment]
It turned out that the root cause was a bug in the driver. A PM4 packet for GDS initialization was not sent to the GPU. (See p. 44 of the following document.) Oh well.

http://amd-dev.wpengine.netdna-cdn.com/wordpress/media/2013/10/si_programming_guide_v2.pdf
