### ISSUE TITLE
Multiple .kernels with common code section?

### ISSUE THREAD

**Issue by russdirks** [CLRX/CLRX-mirror#13]
First of all, thank-you for making this wonderful product available!  The documentation is excellent.  I was wondering if it is possible to have a source file with multiple `.kernel` sections, and some common code that is callable by allkernels?  (I use `s_getpc_b64` and `s_setpc_b64` for subroutine calls).   It seems that you cannot jump across sections.  So I tried including the common code in each `.kernel` with an `.include` statement, but then it complained about symbols being declared twice, even though they are in separate sections.

Do you have any suggestions?

**Comment by matszpk** [comment]
Firstly, only Gallium and ROCm (HSACO) binary formats allow to share common code between kernels (because code of all kernels is in single section). Look up in '.kcode' and '.kcodeend' pseudo-ops (maybe can works good). In AMD OpenCL1.2 and 2.0 binary formats, any kernel code is in separate section. Kernel is not section: just it is object that represents real OpenCL kernel in program.
In AMD OpenCL 1.2/2.0 binary kernel can have many sections (like code, data, config sections), just in these formats kernels are stored in embedded (ELF) binary files.
Currently, symbols have global visibility (visible in all kernels and sections). Symbols can be set many times (except labels, and symbols defined by .equiv or .eqv pseudo-op). Hence, errors while assemblying program. Yoy can put your code in macro and use \@ in symbol names to make symbols unique. Now, I am working over 'scopes' that allow to use symbols which will be visible in defined program code space.

**Comment by russdirks** [comment]
I think I will use the macro method with the @ symbol.

> Now, I am working over 'scopes' that allow to use symbols which will be visible in defined program code space.

Limiting the scope of symbols and labels to the current `.text` section would be a very useful feature.

**Comment by matszpk** [comment]
The scopes has been added. Look at docs.

**Comment by russdirks** [comment]
Looks good.  I just tried a simple example of 2 kernels in one source file, both with the same symbol.  The compiler gave an error of 'symbol already defined'.  So I put each kernel in it's own scope and then it worked ok.  I think it would be a good idea that each kernel would have it's own local scope by default, but for now it is no problem to add those statements in myself.

**Comment by russdirks** [comment]
I think I found a few typos in your documentation.  On line 8 of the first example, it should say `sym2 in 'ala' scope`, right?

        .byte sym2 # put 11, sym2 in ??global?? scope

On line 4 of the second example it should be 
`        .scope another  # open scope **'another'**, parent is global scope`

**Comment by matszpk** [comment]
About that
```
    .byte sym2 # put 11, sym2 in ??global?? scope
```

In this example, just sym2 doesn't exists in 'ala' scope, but was defined in global scope (first scope that is created by assembler).

Second typo has been fixed.

**Comment by russdirks** [comment]
> In this example, just sym2 doesn't exists in 'ala' scope, but was defined in global scope (first scope that is created by assembler).

I guess I don't understand then.  On line 3, sym2 is being defined, and it is in `ala` scope.  Why are you saying it was defined in global scope?

```
.scope ala  # open scope 'ala', parent is global scope
    sym1 = 4
    sym2 = 11     # this is in ala scope, isn't it?
    .byte sym1 # put 4

```

**Comment by matszpk** [comment]
Oh. That rights. Actually, this is not global scope, but 'ala' scope and current scope is 'child'.

**Comment by russdirks** [comment]
I'd like to re-open this.  The testing I did was very simplistic ... everything in one source file.  I have just tried including the same source file into two kernels  (both in the same source file), and I am getting `symbol is already defined` errors.

This is my main source file:

```

.amdcl2
.gpu Tonga
.arch_minor 0
.arch_stepping 0
.driver_version 200406


.kernel kernel1
    .config
        .dims x
        .cws 128, 1, 1
        .sgprsnum 20
        .vgprsnum 76
        .floatmode 0xc0
        .pgmrsrc1 0x00ac02c0
        .pgmrsrc2 0x00000090
        .dx10clamp
        .ieeemode
        .useargs
        .usesetup
        .priority 0
        .arg _.global_offset_0, "size_t", long
        .arg _.global_offset_1, "size_t", long
        .arg _.global_offset_2, "size_t", long
        .arg _.printf_buffer, "size_t", void*, global, , rdonly
        .arg _.vqueue_pointer, "size_t", long
        .arg _.aqlwrap_pointer, "size_t", long
        .arg g_output, "ulong*", structure*, 32, global, restrict volatile
        .arg i, "ulong", ulong
    .text
        .scope x
        .include "test.inc"
        mac1 v0
        .ends
        s_endpgm


#----------------------------------------------------------------------------

.kernel kernel2
    .config
        .dims x
        .cws 128, 1, 1
        .sgprsnum 40
        .vgprsnum 114
        .floatmode 0xc0
        .pgmrsrc1 0x00ac02dc
        .pgmrsrc2 0x0000008c
        .dx10clamp
        .ieeemode
        .useargs
        .priority 0
        .arg _.global_offset_0, "size_t", long
        .arg _.global_offset_1, "size_t", long
        .arg _.global_offset_2, "size_t", long
        .arg _.printf_buffer, "size_t", void*, global, , rdonly
        .arg _.vqueue_pointer, "size_t", long
        .arg _.aqlwrap_pointer, "size_t", long
        .arg g_output, "ulong*", structure*, 32, global, restrict volatile
        .arg i, "ulong", ulong

    .text
        .scope y
        .include "test.inc"
        mac1 v0
        .ends
        s_endpgm

```

And this is the include file:


```
.macro mac1  dstx, dsty
    v_mov_b32           \dstx, dsty
.endm

```

**Comment by matszpk** [comment]
In your include, you define a macro (macros are still in global space). I wa trying compile this code and I got error 'macro already defined'. Just, try separate macros to other include, that will be included only once. I added 'start' label to your include and I didn't get any errors about 'already defined symbols' (scopes works fine across various includes).

**Comment by russdirks** [comment]
Ok, I just did some experimentation, and found that I don't need to put the `include` statement in the `.text` section ... I can put it right at the beginning of the source file, and still be able to use the macros from both kernels, so that will work well for me.
