### ISSUE TITLE
clBuildProgram fails with master branch version

### ISSUE THREAD

**Issue by russdirks** [CLRX/CLRX-mirror#15]
When I was trying out your new _scopes_ feature, I built from source using the master branch because I didn't see any downloadable executables.  My program compiled ok, but clBuildProgram failed with CL_BUILD_PROGRAM_FAILURE (-11).  The build log gave the following information : `Error: Kernel '&__OpenCL_xxx_kernel' initialization failed.`  Did you add many new features to master besides the scopes feature?

My program continues to compile, build and run fine with 0.1.3.  Do you have any suggestions?

**Comment by matszpk** [comment]
I introduced many changes in Amd OpenCL 2.0 generator: 32-bit binaries support, some fixes in archicture identifiers, gdssize config params, new gpuDeviceCodeTables. You should determine from which revision code doesn't works. Try to compare binaries and find some differences (like, `.note' section diffs).

**Comment by matszpk** [comment]
In current master assembler by default generates binaries for 32-bit AMD OpenCL 2.0 binary format. Use option '-6' to generate 64-bit binaries.

**Comment by russdirks** [comment]
> In current master assembler by default generates binaries for 32-bit AMD OpenCL 2.0 binary format. Use option '-6' to generate 64-bit binaries.

That fixed it.
