### ISSUE TITLE
Enforce "at most one SGPR per Vector ALU instruction"

### ISSUE THREAD

**Issue by preda** [CLRX/CLRX-mirror#16]
clrxasm accepts as correct:
v_mul_f64 v[0:1], s[0:1], v[0:1]

But this reads two SGPRs, while according to GCN3 ISA 6.2.1 "at most 1 SGRP can be read per instruction". If that restriction stands, it would be nice to report an error.

**Comment by matszpk** [comment]
Using two scalar registers in single argument in vector instructions is correct. Just, some instructions can read 64-bit data from two scalar registers, if these two scalar registers given in this same operand.

**Comment by preda** [comment]
OK, thank you for clarifying this, then the problem is in AMD's ISA documentation.
