### ISSUE TITLE
Broken links in the table of contents of the online manual.

### ISSUE THREAD

**Issue by zawawawa** [CLRX/CLRX-mirror#18]
Just to let you know, internal links on the following pages are all broken as far back as I could remember:

https://github.com/CLRX/CLRX-mirror/blob/master/doc/ClrxToc.md
https://github.com/CLRX/CLRX-mirror/blob/master/doc/GcnIsa.md

All you need to do is to add the ".md" extension to each link. Thank you as always for a tremendously useful piece of software!

**Comment by matszpk** [comment]
The real CLRX Manual is available on:

https://github.com/CLRX/CLRX-mirror/wiki
http://clrx.nativeboinc.org/wiki/wiki/ClrxToc

and also in binary packages (but updated to last release).
Moreover, you can build manual from CLRX sources if you will install markdown_py.

**Comment by zawawawa** [comment]
Ah, I see... Thanks!
