### ISSUE TITLE
PGMRSRC2 handling

### ISSUE THREAD

**Issue by zawawawa** [CLRX/CLRX-mirror#19]
CLRX's current handling of PGMSRC2 does not seem compatible with Adrenaline 18.3.4 on Windows 10. The driver version is "OpenCL 2.1 AMD-APP (2527.10)". My binary kernel, which was created by the driver from an OpenCL source code, shows the following parameters when disassembled with clrxdisasm:

```
.localsize 4096
.floatmode 0xc0
.scratchbuffer 1088
.pgmrsrc1 0x00ac0117
.pgmrsrc2 0x00000891
```

However, when I assembled this disassembled source code, clrxasm changes the value of PGMRSRC2 from 0x00000891 to 0x00000091, and the kernel crashes the whole system.

Now, here is the CLRX code in question:

```
uint32_t CLRX::calculatePgmRSrc2(GPUArchitecture arch, bool scratchEn, cxuint userDataNum,
            bool trapPresent, cxuint dimMask, cxuint defDimValues, bool tgSizeEn,
            cxuint ldsSize, cxuint exceptions)
{
    // GCN1.1 and later have 512 byte banks instead 256
    const cxuint ldsShift = arch<GPUArchitecture::GCN1_1 ? 8 : 9;
    const uint32_t ldsMask = (1U<<ldsShift)-1U;
    uint32_t dimValues = 0;
    // calculate dimMask (TGID_X_EN, ..., TIDIG_COMP_CNT fields)
    if (dimMask != UINT_MAX)
        dimValues = ((dimMask&7)<<7) | (((dimMask&4) ? 2 : (dimMask&2) ? 1 : 0)<<11);
    else // use default value for dimensions
        dimValues = defDimValues;
    return uint32_t(scratchEn ? 1U : 0U) | (uint32_t(userDataNum)<<1) |
            dimValues | (tgSizeEn ? 0x400U : 0U) | (trapPresent ? 0x40U : 0U) |
            (((uint32_t(ldsSize+ldsMask)>>ldsShift)&0x1ff)<<15) |
            ((uint32_t(exceptions)&0x7f)<<24);
}
```
This code segment does not seem compatible with my disassembled source code. To be more specific, with ldsSize = 4096, `(((uint32_t(ldsSize+ldsMask)>>ldsShift)&0x1ff)<<15)` would be 0x40000 instead of 0x800.

**Comment by matszpk** [comment]
In this case, the TIDIG_COMP_CNT (number of the VGPRs that holds local ids) is incorrectly set by my assembler. The CLRX assembler automatically set this value based on '.dims' settings. Also, the TGID_X_EN|TGID_Y_EN|TGID_Z_EN (enabled dimesions of group_ids for SGPRs) are set by '.dims'. In your case, the code uses only the first SGPR (X dimesion) and '.dims' should be determine by disassembler as 'x' (the first dimension). Maybe, the setting dimesions of group_ids and local_ids is wrong.
Some other wrong things can be caused while merging PGMRSRCs and other settings: breaking VGPRs and SGPRs number (in your case this is not done).

Firstly, I recommend yet another try, without PGMRSRC1 and PGMRSRC2 setting. I will check how kernel codes from the current AMD OpenCL driver version behaves after reassemblying.

**Comment by matszpk** [comment]
About LDS setting in PGMRSRC2, in the AMDOCL2 format, the LDS size is not set main PGMRSRC2 value. AMDOCL2 hold two PGMRSRC2 values and one holds correct LDS size. The assembler always set correct LDS size when you give '.localsize' pseudo-op.

**Comment by matszpk** [comment]
Hey, Does 11bit in PGMRSRC2 causes crash? If yes, I will next needed pseudo-op to my assembler to set group_ids and local_ids dimensions independently, or extend same '.dims' to make this same in '.dims'.

**Comment by matszpk** [comment]
I compiled by AMDGPU-PRO 18.10 driver my sample kernels with scratch buffers and local size and I didn't find the enabled 11bit in PGMRSRC2 (for Vega and Ellesmere). For me, this is enough weird setup.

**Comment by matszpk** [comment]
Wrong. In current AMDOCL2 binary only one PGMRSRC2 is present. Old unusable version of this format had two values. My error. I remembler, that has two PGMRSRC2 values. In new AMDOCL2 the LDS size is never set in PGMRSRC2 in kernel setup.

**Comment by zawawawa** [comment]
I finally got a chance to try the latest updates, and everything looks great. Thank you!
