### ISSUE TITLE
clrxdisasm: Kernel ArgEntry size doesn't match

### ISSUE THREAD

**Issue by meriken** [CLRX/CLRX-mirror#2]
[OpenCL12.zip](https://github.com/CLRX/CLRX-mirror/files/213429/OpenCL12.zip)

I wasn't able to disassemble a binary file created by the most recent AMD driver with the following error message:

Error during disassemblying 'OpenCL12GCN.bin': Kernel ArgEntry size doesn't match

My system configuration is as follows:

OS: Windows 7 SP1 64bit
GPU: R9 290X
CLRX Version: Latest on GitHub
Driver Version: non-whql-64bit-radeon-software-crimson-16.4.1-win10-win8.1-win7-apr4

**Comment by matszpk** [comment]
I made hot fix for that driver version.
