### ISSUE TITLE
Glitch in clrxasm's macro expansion

### ISSUE THREAD

**Issue by zawawawa** [CLRX/CLRX-mirror#21]
I might be missing something, but I thought I should report anyway.
For some unknown reason, the following code results in an error with the "-g Ellesmere" option:
````````````````
        exec_masc = %s[47:48]
            :
        s_and_saveexec_b64 exec_masc, vcc
````````````````
````````````````
GCN3_ethash_LWS256.isa:833:28: Error: Required 2 scalar registers
````````````````
There seems to be a glitch in macro expansion as the following code is fine:
````````````````
s_and_saveexec_b64 s[47:48], vcc
````````````````

**Comment by matszpk** [comment]
Thank you for reporting bug. Now it has been fixed in next commit.

**Comment by matszpk** [comment]
exec_masc = %s[47:48]. 64-bit operand in SOP1 should be aligned (based on ISA doc). Correctly should be %s[48:49] or %s[46:47].

**Comment by zawawawa** [comment]
That was my bad... The same error happened with `%s[46:47]`, too, though.

**Comment by matszpk** [comment]
Ok. glitch has been fixed. Assembler incorrectly assumed that exec_masc was exec_lo or exec_hi register and it checked required register number (and print error because _lo or _hi single register). Now assembler know that is register-symbol. This was reason why assembler print that error.

**Comment by zawawawa** [comment]
Thank you so much!
