### ISSUE TITLE
clrxdisasm segmentation fault

### ISSUE THREAD

**Issue by eXtremal-ik7** [CLRX/CLRX-mirror#24]
[sieve.bin.zip](https://github.com/CLRX/CLRX-mirror/files/3411771/sieve.bin.zip)

`Starting program: /home/user/build/CLRX-mirror/x86_64-Linux/programs/clrxdisasm ~/build/xpmclient/src/xpm/opencl/sieve.bin
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
/* Disassembling '/home/user/build/xpmclient/src/xpm/opencl/sieve.bin' */
.rocm
.gpu GFX900
.arch_minor 0
.arch_stepping 0
.eflags 44
.newbinfmt
.target "amdgcn-amd-amdhsa-amdgizcl-gfx900"
.kernel _Z12get_group_idj
    .fkernel
.kernel _Z12get_local_idj
    .fkernel
.kernel _Z5mad24jjj
    .fkernel
.kernel _Z7barrierj
    .fkernel
.kernel _Z9atomic_orPVjj
    .fkernel
.kernel s_sieve
.kernel setup_sieve
.kernel sieve
.text

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7a72384 in CLRX::ULEV (t=<error reading variable>) at /home/user/build/CLRX-mirror/CLRX/utils/MemAccess.h:493
493     { return t; }
(gdb) bt
#0  0x00007ffff7a72384 in CLRX::ULEV (t=<error reading variable>) at /home/user/build/CLRX-mirror/CLRX/utils/MemAccess.h:493
#1  0x00007ffff7ac768e in CLRX::GCNDisassembler::analyzeBeforeDisassemble (this=0x5555557763f0) at /home/user/build/CLRX-mirror/amdasm/GCNDisasm.cpp:329
#2  0x00007ffff7a9ede3 in CLRX::disassembleAMDHSACode (output=..., regions=std::vector of length 8, capacity 8 = {...}, codeSize=66040, code=0x55555577b070 "\001", isaDisassembler=0x5555557763f0, flags=513) at /home/user/build/CLRX-mirror/amdasm/DisasmROCm.cpp:479
#3  0x00007ffff7aa16c4 in CLRX::disassembleROCm (output=..., rocmInput=0x555555776720, isaDisassembler=0x5555557763f0, flags=513) at /home/user/build/CLRX-mirror/amdasm/DisasmROCm.cpp:955
#4  0x00007ffff7a721f4 in CLRX::Disassembler::disassemble (this=0x7fffffffda30) at /home/user/build/CLRX-mirror/amdasm/Disassembler.cpp:636
#5  0x000055555555ca76 in main (argc=2, argv=0x7fffffffdd48) at /home/user/build/CLRX-mirror/programs/clrxdisasm.cpp:188`

**Comment by matszpk** [comment]
I prepared hot fix for that ROCm binaries. It will be available on github few minutes later (github repo is updated for every 15 minutes).

**Comment by matszpk** [comment]
hot fix is now available on github.

**Comment by eXtremal-ik7** [comment]
segfault fixed, issue can be closed, thanks
