### ISSUE TITLE
RDNA Support?

### ISSUE THREAD

**Issue by lukinma** [CLRX/CLRX-mirror#26]
Do you have any plans to support new RDNA architecture?

**Comment by Melirius** [comment]
Yes, latest commits of the author are all about that. But when it will be available, I do not know.

**Comment by matszpk** [comment]
Yes. CLRadeonExtender from SVN or github just supports RDNA (Navi) architecture. Moreover, I added support for new OpenCL binary format for AMDOCL driver (still untested due to lack of the hardware by me).
