### ISSUE TITLE
Disassembler: SMRD offsets on SI/CI

### ISSUE THREAD

**Issue by daniel-schuermann** [CLRX/CLRX-mirror#27]
Hey,
thanks for the great work! I currently use the CLRX disassembler to debug my SI/CI implementation for RADV/ACO (llvm-mc doesn't provide a disassembler for these generations for some reason).

What I came across is that the SMRD offsets are dword offsets on SI/CI, so I would suggest to shift them to represent the matching byte-offsets. Additionally, SMRD instructions support literal offsets in the next dword when imm==0 and the SGPR is 0xFF. These again are dword offsets as testing confirmed. Currently, clrx doesn't detect the literal offsets but prints 0x0 for offset and reads the next dword as instruction.

Not urgent, would be just nice to have. You can also pinpoint me, then I'll probably add a PR when I find time.

**Comment by matszpk** [comment]
The dword offsets are from SI/CI ISA documents and GCN disassembler from older AMD OpenCL drivers. I recommend to use our symbol to convert offset to byte for later ISA version by using conditional assemblying ('.ifarch' etc). Mainly CLRX assembler and disassembler syntax based on that AMD OpenCL driver's disassembler where were some bugs in disassembler while decoding some instructions and encoding.
The SMRD for SI/CI have only 4 bytes (single dword), so an offset in SMRD is only 8 bits. Specific case when imm=0 and SGPR is 0xff (immediate literal) is not tested by me and that was not noticed in ISA document. Maybe later this case will be checked. I don't know whether this case is correct for SI/CI ISA.
The VI (Fiji, GCN 1.2) introduces SMEM encoding that have an extra dword for offset and other encoding stuff.

**Comment by daniel-schuermann** [comment]
Thanks for the quick response.
Maybe I should have expressed it better. We don't use CLRX to assemble anything. RADV/ACO is a Vulkan driver and part of the Mesa3d project. We have our own assembler and write the instruction stream ourselves. I only use it to disassemble the instructions again for debugging purposes (using --gpuType=GFX701 -r).

Would it be possible to change the disassembler to print byte offsets or would this cause issues with the assembler? And the immediate literal is mentioned in Table 7.1 in the CI ISA doc: 
> This field also can be set to SQ_SRC_LITERAL, indicating that the offset is specified in a 32-bit literal constant.

I tested it, and it works, it's just disassembled incorrectly.

**Comment by matszpk** [comment]
Actually. In CI ISA Docs is written that SMRD can have extra dword with immediate literal, but no SI. Thank you for reporting bug.

**Comment by matszpk** [comment]
Latest revision add preliminary support for this specific feature for GCN1.1 (CI). If you want to force literal just use "lit(xxx)" in encoding.
