### ISSUE TITLE
Difficulty dissasembling ROCm 3.3 RadeonVII output

### ISSUE THREAD

**Issue by preda** [CLRX/CLRX-mirror#28]
I'm compiling a binary kernel for RadeonVII (gfx906, Vega20) using ROCm 3.3. When I try to disassembly the binary dump, I get the wrong disassembly as if the GCN version is wrong. I tried all variants of specifying the version: -A GCN1.4.1 , -t 309800, -g GFX906 but nothing seems to trigger the proper disassembly.

The disassembly header reports:
```
/* Disassembling '/home/preda/gpuowl/tmp0/5M_0_gfx906.so' */
.rocm
.gpu GFX1010
.arch_minor 1
.arch_stepping 0
.eflags 559
.llvm10binfmt
.metadatav3
```
But later on a
```
s_mul_hi_u32 s0, s6, 0xcccccccd
```
is disassembled as
```
s_absdiff_i32   s0, s6, 0xcccccccd
```

What is the proper way to disassemble RadeonVII from ROCm 3.3?

**Comment by matszpk** [comment]
Now, it should be working (in current commit). I added ability to set GPU device type when LLVM10 binary format detected.

**Comment by preda** [comment]
Thanks!
