### ISSUE TITLE
LLVM 3.9 uses 64 bit ELF for Gallium

### ISSUE THREAD

**Issue by laanwj** [CLRX/CLRX-mirror#3]
I tried `clrxdisasm` on the output of git mesa+llvm, and it's complaining that the ELF class is not 32-bit. It indeed appears that it has been changed to 64-bit.

After converting GalliumElfBinary's superclass ElfBinary64 it worked again.
This works as a hack. However, handling both types of ELF would be a bit more difficult.

Edit: thinking more about this, the reason that this uses ELF64 could also be that this card is a `Tonga PRO [Radeon R9 285/380]`, for which support was only added recently, the reason I had to use such a recent version in the first place.

**Comment by matszpk** [comment]
Added support for ELF64 to assembler and disassembler.

**Comment by laanwj** [comment]
Verified that it works. This is great, thanks.
