### ISSUE TITLE
Disassembly of ROCm 4.2 output produces error 

### ISSUE THREAD

**Issue by preda** [CLRX/CLRX-mirror#35]
Using a fresh build of clrxdisasm (reports version 0.1.9),
when trying to disassemble the binary probuduced by ROCm 4.2 (OpenCL), produces the following error:
```
/* Disassembling 'dump.bin' */
/* ERROR for 'dump.bin' */
Error during disassemblying 'dump.bin': Kernels number is too big!
```

The binary is attached.

[dump.bin.txt](https://github.com/CLRX/CLRX-mirror/files/6643777/dump.bin.txt)

**Comment by matszpk** [comment]
Fixed. Elf reader just can't read Elf binaries with newer ABI version.

**Comment by preda** [comment]
Thanks!
