### ISSUE TITLE
support gcn1.2 in sample program

### ISSUE THREAD

**Issue by nerdralph** [CLRX/CLRX-mirror#9]
GenericPtr uses instructions that are supported on gcn1.2 (the assembler even recognizes v_add_i32 as a valid instruction along with v_add_u32).  Since the assembler supports 1.2, it would be good to have at least one sample program for it.

**Comment by matszpk** [comment]
Thank you for advice. Currently I have no GCN 1.2 device (only Bonaire and Pitcairn) to test samples. Porting to GCN 1.2 requires slightly more to do than checking what instructions can be used (different offset in SMEM instructions, other instructions in 64-bit memory access, etc).

**Comment by matszpk** [comment]
Samples has been updated. However, I didn't make any tests on GCN 1.2 devices, because I have not these graphics cards.

**Comment by nerdralph** [comment]
Looks good!
`
CLRX-mirror/build/samples$ ./GenericPtr
Device: 0 - Tonga
BinaryFormat: AMD OpenCL 2.0
Bitness: 64
Results is OK
`
